{% set name = "autoflake" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef7c496d9bce9d2cef049f24e482d1d3090c37fbd44e5e85dfb00db3c78ee16c

build:
  number: 0
  noarch: python
  entry_points:
    - autoflake = autoflake:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - pyflakes >=3.0.0
    - python >={{ python_min }}
    - tomli >=2.0.1 # remove when python <=3.10 is no longer supported

test:
  requires:
    - python {{ python_min }}
  imports:
    - autoflake
  commands:
    - autoflake --help

about:
  home: https://github.com/myint/autoflake
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Removes unused imports and unused variables

extra:
  recipe-maintainers:
    - pmgrafe
    - asford
