{% set name = "autoflake" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c98b75dc5b0a86459c4f01a1d32ac7eb4338ec4317a4469515ff1e687ecd909e

build:
  number: 0
  noarch: python
  entry_points:
    - autoflake = autoflake:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pyflakes >=1.1.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - autoflake --help

about:
  home: https://github.com/myint/autoflake
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Removes unused imports and unused variables

extra:
  recipe-maintainers:
    - pmgrafe
    - asford
