{% set name = "autoflake" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1e6d0b1f1bbeead5ffa96b1c5b076b627eb5bfb8712599d8e5c465863ab246b

build:
  number: 0
  noarch: python
  entry_points:
    - autoflake = autoflake:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - pyflakes >=1.1.0
    - python >=2.7

test:
  commands:
    - autoflake --help

about:
  home: https://github.com/myint/autoflake
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Removes unused imports and unused variables

extra:
  recipe-maintainers:
    - pmgrafe
    - asford
