{% set name = "autoflake" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2782169b0bdb7f887d15158053b8481bbcb0dd4d7325c035f49b4cd1f7cdb1c7

build:
  number: 0
  noarch: python
  entry_points:
    - autoflake = autoflake:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - pyflakes >=1.1.0
    - python >=2.7

test:
  commands:
    - autoflake --help

about:
  home: https://github.com/myint/autoflake
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Removes unused imports and unused variables

extra:
  recipe-maintainers:
    - pmgrafe
    - asford
